
import React, { useState } from "react";
import type { ChangeEvent } from "react";
import { useValidation } from "@/hooks/useValidation";
import Input from "@/components/ui/Input";
import Button from "@/components/ui/Button";
import { useAuth } from "@/hooks/useAuth";
import { useZxing } from "react-zxing";
import "./ValidationPortal.css";

const ValidationPortal: React.FC = () => {
  const [codeInput, setCodeInput] = useState("");
  const [showQRScanner, setShowQRScanner] = useState(false);
  const [visibleCount, setVisibleCount] = useState(5);

  const { state, result, errorMessage, validate, validateQR, history, reset } = useValidation();
  const { logout, user } = useAuth();

  const officerName = user
    ? `${user.firstName ?? ""} ${user.lastName ? user.lastName.charAt(0) + "." : ""}`
    : "Guest";

  const handleValidationSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (codeInput.length === 5 && state !== "loading") {
      validate(codeInput);
    }
  };

  const handleQRScan = async (data: string) => {
    if (data) {
      setShowQRScanner(false);
      
      // Sanitize the data from the QR scanner.
      // It might be a URL or other string containing the code.
      // We look for a 5-character alphanumeric sequence.
      const match = data.toUpperCase().match(/[A-Z0-9]{5}/);
      const sanitizedCode = match ? match[0] : null;

      if (sanitizedCode) {
        await validateQR(sanitizedCode);
      } else {
        // Handle invalid QR code data
        console.error("Invalid QR code data: Could not find a 5-character code in", data);
      }
    }
  };

  const { ref: videoRef } = useZxing({
    onDecodeResult(result) {
      if (result) handleQRScan(result.getText());
    },
    paused: !showQRScanner,
  });

  const closeModal = () => {
    reset();
    setCodeInput("");
  };

  const renderModal = () => {
    if (state === "success" && result) {
      return (
        <div className="overlay fade-in">
          <div className="modal-card success pop-in">
            <h2>ACCESS GRANTED ✅</h2>
            <p>Generated by: <strong>{result.residentName}</strong></p>
            <p>Home: <strong>{`${result.homeDetails?.plotNumber ?? ""} ${result.homeDetails?.street ?? ""}`}</strong></p>
            <p>Visitor: <strong>{result.visitorName}</strong></p>
            <Button onClick={closeModal}>OK</Button>
          </div>
        </div>
      );
    }
    if (state === "denied" || state === "error") {
      return (
        <div className="overlay fade-in">
          <div className="modal-card error pop-in">
            <h2>ACCESS DENIED ❌</h2>
            <p>{errorMessage || "Invalid access code"}</p>
            <Button onClick={closeModal} variant="danger">OK</Button>
          </div>
        </div>
      );
    }
    return null;
  };

  return (
    <div className="validation-page">
      <header className="validation-header">
        <div>
          <h1>Security Validation Portal</h1>
          <p>Officer: <strong>{officerName}</strong></p>
        </div>
        <div className="header-right">
          <p className="timestamp">
            {new Date().toLocaleDateString("en-US", {
              weekday: "short",
              month: "short",
              day: "numeric",
            })}{" "}
            {new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
          </p>
          <button onClick={logout} className="logout-btn">LOGOUT</button>
        </div>
      </header>

      <main className="validation-main slide-up">
        <div className="form-split">
          {showQRScanner && (
            <div className="scanner-container fade-in">
              <video ref={videoRef} className="scanner-video" />
              <p className="info-text">Scanning... Hold your QR code steady.</p>
            </div>
          )}

          <div className="form-container fade-in">
            <h3>Validate Access Code</h3>
            <form onSubmit={handleValidationSubmit} className="form">
              <Input
                label="Access Code"
                type="text"
                maxLength={5}
                value={codeInput.toUpperCase()}
                onChange={(e: ChangeEvent<HTMLInputElement>) => setCodeInput(e.target.value.toUpperCase())}
                placeholder="Enter Access Code"
              />
              <Button type="submit" disabled={state === "loading"}>
                {state === "loading" ? "Validating..." : "VALIDATE"}
              </Button>
            </form>

            <Button
              onClick={() => setShowQRScanner(!showQRScanner)}
              className="qr-toggle-btn fade-in"
            >
              {showQRScanner ? "Close Scanner" : "Scan QR Code"}
            </Button>
          </div>
        </div>
      </main>

      <section className="table-section fade-in">
        <h3>Recent Validations</h3>
        <div className="table-wrapper">
          <table className="validation-table">
            <thead>
              <tr>
                <th>Time</th>
                <th>Code</th>
                <th>Visitor</th>
                <th>Resident</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {history.length > 0 ? (
                history.slice(0, visibleCount).map((log) => (
                  <tr key={log.id} className="row-fade">
                    <td>{new Date(log.validated_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</td>
                    <td>{log.code}</td>
                    <td>{log.visitor_name}</td>
                    <td>{log.resident_name || "N/A"}</td>
                    <td className={log.result === "granted" ? "status-granted" : "status-denied"}>
                      {log.result ? log.result.toUpperCase() : "N/A"}
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={5} className="no-data">No recent validations</td>
                </tr>
              )}
            </tbody>
          </table>

          {history.length > 5 && (
            <div className="load-more">
              <Button onClick={() => setVisibleCount((prev) => prev >= history.length ? 5 : prev + 5)}>
                {visibleCount >= history.length ? "Show Less" : "Load More"}
              </Button>
            </div>
          )}
        </div>
      </section>

      {renderModal()}
    </div>
  );
};

export default ValidationPortal;
